Error handling for invalid date parameter
Also fix build (I forgot to commit expected test output)

diff --git a/src/pottery-post b/src/pottery-post
--- a/src/pottery-post
+++ b/src/pottery-post
@@ -29,12 +29,19 @@ eval "$($(dirname $0)/pottery-config)"
 ##     pottery post -d 2018-08-23T13:42:00T We now do trunk-based development instead of pull requests
 ##
 
+date_format="%Y-%m-%dT%H:%M:%SZ"
+date_pattern='[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z'
 
 while getopts t: arg
 do
     case "$arg" in
         t)
             date_time="$OPTARG"
+			if ! echo $date_time | grep -Eq "$date_pattern"
+			then
+			    echo "Invalid date time" >&2
+				exit 1
+			fi
             ;;
         --)
             break
@@ -49,7 +56,7 @@ shift $((OPTIND-1))
 
 if [ -z $date_time ]
 then
-	date_time=${TEST_TIME:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}
+	date_time=${TEST_TIME:-$(date -u +$date_format)}
 fi
 
 date_y=${date_time:0:4}
